/**
* 
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package ru.tinkoff.fintech.model


/**
 * 
 * @param cardNumber 
 * @param client 
 * @param id 
 * @param loyaltyProgram 
 */
data class Card (
    val cardNumber: kotlin.String,
    val client: kotlin.String,
    val id: kotlin.String,
    val loyaltyProgram: kotlin.String
) {

}

